name: Download and Save Text

on:
  push:
    branches:
      - main

jobs:
  download_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Download text from link
        run: |
          curl -sSL "${{ env.LINK_URL }}" > downloaded_text.txt

      - name: Append text to existing file
        run: |
          echo "${{ steps.download_text.outputs.text }}" >> existing_file.txt

      - name: Set secrets
        run: |
          echo "::set-output name=DownloadedText::$(cat downloaded_text.txt)"

      - name: Cleanup
        run: rm downloaded_text.txt
