name: Update Data

on:
  schedule:
    - cron: "0 */2 * * *"  # هر دو ساعت اجرا می شود

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Update data
        run: |
          # Replace with your actual data fetching and processing code
          curl -s "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/channels" | jq . > chanels.txt
          curl -s "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/subscribe" | jq . > subs.txt

      - name: Commit and push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "Update data from links"
          push: true
